name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]
env:
  APP_SLUG: testappscreen68-1746428430357
  PROJECT_ID: stellar-benefit-457920-v3
  REGION: asia-northeast1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id:       ${{ env.PROJECT_ID }}
          create_credentials_file: true
          export_environment_variables: true
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Build & Push Docker image
        run: |
          gcloud builds submit \
            --project=${{ env.PROJECT_ID }} \
            --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_SLUG }} \
            || (echo "⚠️ Cloud Build log streaming failed—continuing anyway" && exit 0)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP_SLUG }}             --project=${{ env.PROJECT_ID }}             --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_SLUG }}             --platform managed             --region ${{ env.REGION }}             --allow-unauthenticated             --timeout 300s